const naam = "Daan Parker";
let leeftijd = 19;

console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
console.log("mijn naam is " + naam + " en ik ben " + leeftijd + " jaar oud");
leeftijd = leeftijd + 1;
